name: pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt
      -
        name: Run tests
        run: |
          pytest ./python -v --import-mode=importlib
